### ISSUE TITLE
Bonk~ on new MacBook Pro (2021 - Apple M1)

### ISSUE THREAD

**Issue by nani42** [v7b1/bonk_64bit-version#1]
Hi there!
I keep getting the following error message when creating a new [bonk~] object in Max 8: "bonk~: could not load due to incorrect architecture". The object itself gets autofilled when I type in the word "bonk~" and all the help files and documentation are there but the object itself always stays yellow and doesn't work.
I'm using one of the new MacBook Pros that came out this autumn with the Apple M1 Max chip. Could this issue be due to incompatibility with my chip aka OSX ARM64?
Thanks!

**Comment by nani42** [comment]
I am having the same issue with [fiddle~] and [sigmund~] also!

**Comment by v7b1** [comment]
yes, the externals need to be recompiled to run natively on M1/ARM. Unfortunately this won't happen any time soon on my side. But apart from that you can launch Max in rosetta mode and the provided binaries should work.

**Comment by nani42** [comment]
I see - okay thank you, I will stick with Rosetta Mode for now then!

**Comment by v7b1** [comment]
Hi, in the meantime the ARM version was done (actually two years ago already...), so I'm closing this now.
